=== OSAMES/ORM/OsamesMicroOrm/Config/xml_schemas/omo-mapping.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--/*
This file is part of OSAMES Micro ORM.
Copyright 2014 OSAMES

OSAMES Micro ORM is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OSAMES Micro ORM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with OSAMES Micro ORM.  If not, see <http://www.gnu.org/licenses/>.
*/-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.osames.org/osamesorm"
  xmlns:orm="http://www.osames.org/osamesorm" targetNamespace="http://www.osames.org/osamesorm"
  elementFormDefault="qualified">
  <xs:element name="Tables" type="typeTable" />
  <xs:complexType name="typeTable">
    <xs:sequence>
      <xs:element name="Table" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="MappingObject" minOccurs="1" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="column" type="xs:string" use="required" />
                <xs:attribute name="property" type="xs:string" use="required" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="name" type="xs:string" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== OSAMES/ORM/TestOsamesMicroOrmSqlite/TestConfigSqlite/mapping-potential-sql-injection.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--/*
This file is part of OSAMES Micro ORM.
Copyright 2014 OSAMES

OSAMES Micro ORM is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OSAMES Micro ORM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with OSAMES Micro ORM.  If not, see <http://www.gnu.org/licenses/>.
*/-->

<!-- This test incorrect mapping set a non-existent column which name could lead for SQL injections, for Customer property "FirstName"  -->

<orm:Tables xmlns:orm="http://www.osames.org/osamesorm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.osames.org/osamesorm xml_schemas\omo-mapping.xsd">
  <orm:Table name="Customer">
    <orm:MappingObject property="CustomerId" column="CustomerId"/>
    <orm:MappingObject property="FirstName" column="FirstName, 'FirstName'"/>
  	<orm:MappingObject property="LastName" column="Last_Name"/>
  	<orm:MappingObject property="Company" column="Company"/>
  	<orm:MappingObject property="Address" column="Address"/>
  	<orm:MappingObject property="City" column="City"/>
  	<orm:MappingObject property="State" column="State"/>
  	<orm:MappingObject property="Country" column="Country"/>
  	<orm:MappingObject property="PostalCode" column="Postal-Code"/>
  	<orm:MappingObject property="Phone" column="Phone"/>
  	<orm:MappingObject property="Fax" column="Fax"/>
  	<orm:MappingObject property="Email" column="Email"/>
  	<orm:MappingObject property="SupportRepId" column="SupportRepId"/>
  </orm:Table>
  <orm:Table name="Track">
    <orm:MappingObject property="TrackId" column="TrackId"/>
  </orm:Table>
</orm:Tables>

=== OSAMES/ORM/OsamesMicroOrm/Config/omo-mapping.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--/*
This file is part of OSAMES Micro ORM.
Copyright 2014 OSAMES

OSAMES Micro ORM is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OSAMES Micro ORM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with OSAMES Micro ORM.  If not, see <http://www.gnu.org/licenses/>.
*/-->
<!-- effectively used mapping  -->
<orm:Tables xmlns:orm="http://www.osames.org/osamesorm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.osames.org/osamesorm xml_schemas\omo-mapping.xsd">
  <orm:Table name="Customer">
    <orm:MappingObject property="CustomerId" column="CustomerId"/>
    <orm:MappingObject property="FirstName" column="FirstName"/>
  	<orm:MappingObject property="LastName" column="LastName"/>
  	<orm:MappingObject property="Company" column="Company"/>
  	<orm:MappingObject property="Address" column="Address"/>
  	<orm:MappingObject property="City" column="City"/>
  	<orm:MappingObject property="State" column="State"/>
  	<orm:MappingObject property="Country" column="Country"/>
  	<orm:MappingObject property="PostalCode" column="PostalCode"/>
  	<orm:MappingObject property="Phone" column="Phone"/>
  	<orm:MappingObject property="Fax" column="Fax"/>
  	<orm:MappingObject property="Email" column="Email"/>
  	<orm:MappingObject property="SupportRepId" column="SupportRepId"/>
  </orm:Table>
  <orm:Table name="Track">
  	<orm:MappingObject property="TrackId" column="TrackId"/>
  	<orm:MappingObject property="Name" column="Name"/>
  	<orm:MappingObject property="AlbumId" column="AlbumId"/>
  	<orm:MappingObject property="MediaTypeId" column="MediaTypeId"/>
  	<orm:MappingObject property="GenreId" column="GenreId"/>
  	<orm:MappingObject property="Composer" column="Composer"/>
  	<orm:MappingObject property="Milliseconds" column="Milliseconds"/>
    <orm:MappingObject property="Bytes" column="Bytes"/>
    <orm:MappingObject property="UnitPrice" column="UnitPrice"/>
  </orm:Table>
  <!--<orm:Table name="InvoiceLine">
  	<orm:MappingObject property="" column="InvoiceLineId"/>
  	<orm:MappingObject property="" column="InvoiceId"/>
  	<orm:MappingObject property="" column="TrackId"/>
  	<orm:MappingObject property="" column="UnitPrice"/>
  	<orm:MappingObject property="" column="Quantity"/>
  </orm:Table>
  <orm:Table name="Invoice">
  	<orm:MappingObject property="" column="InvoiceId"/>
  	<orm:MappingObject property="" column="CustomerId"/>
    <orm:MappingObject property="" column="InvoiceDate"/>
    <orm:MappingObject property="" column="BillingAddress"/>
    <orm:MappingObject property="" column="BillingCity"/>
    <orm:MappingObject property="" column="BillingState"/>
    <orm:MappingObject property="" column="BillingCountry"/>
    <orm:MappingObject property="" column="BillingPostalCode"/>
    <orm:MappingObject property="" column="Total"/>
  </orm:Table>
  <orm:Table name="Employee">
  	<orm:MappingObject property="" column="EmployeeId"/>
  	<orm:MappingObject property="" column="LastName"/>
  	<orm:MappingObject property="" column="FirstName"/>
  	<orm:MappingObject property="" column="Title"/>
  	<orm:MappingObject property="" column="ReportsTo"/>
  	<orm:MappingObject property="" column="BirthDate"/>
    <orm:MappingObject property="" column="HireDate"/>
    <orm:MappingObject property="" column="Address"/>
    <orm:MappingObject property="" column="City"/>
    <orm:MappingObject property="" column="State"/>
    <orm:MappingObject property="" column="Country"/>
    <orm:MappingObject property="" column="PostalCode"/>
    <orm:MappingObject property="" column="Phone"/>
    <orm:MappingObject property="" column="Fax"/>
    <orm:MappingObject property="" column="Email"/>
  </orm:Table>-->
</orm:Tables>

=== OSAMES/ORM/TestOsamesMicroOrmMsSql/TestConfigMsSql/incorrect-mapping.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--/*
This file is part of OSAMES Micro ORM.
Copyright 2014 OSAMES

OSAMES Micro ORM is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OSAMES Micro ORM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with OSAMES Micro ORM.  If not, see <http://www.gnu.org/licenses/>.
*/-->

<!-- This test incorrect mapping set a non-existent column : "IdCustomer", instead of "CustomerId", for Customer property "CustomerId"  -->

<orm:Tables xmlns:orm="http://www.osames.org/osamesorm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.osames.org/osamesorm xml_schemas\omo-mapping.xsd">
  <orm:Table name="Customer">
    <!-- wrong "IdCustomer" column (but property is OK) -->
    <orm:MappingObject property="IdCustomer" column="IdCustomer"/>
    <orm:MappingObject property="FirstName" column="FirstName"/>
  	<orm:MappingObject property="LastName" column="LastName"/>
  	<orm:MappingObject property="Company" column="Company"/>
  	<orm:MappingObject property="Address" column="Address"/>
  	<orm:MappingObject property="City" column="City"/>
  	<orm:MappingObject property="State" column="State"/>
  	<orm:MappingObject property="Country" column="Country"/>
  	<orm:MappingObject property="PostalCode" column="PostalCode"/>
  	<orm:MappingObject property="Phone" column="Phone"/>
  	<orm:MappingObject property="Fax" column="Fax"/>
  	<orm:MappingObject property="Email" column="Email"/>
  	<orm:MappingObject property="SupportRepId" column="SupportRepId"/>
  </orm:Table>

  <orm:Table name="Employee">
    <orm:MappingObject property="EmployeeId" column="EmployeeId"/>
    <orm:MappingObject property="LastName" column="LastName"/>
    <orm:MappingObject property="FirstName" column="FirstName"/>
    <orm:MappingObject property="BirthDate" column="LastName"/>
  </orm:Table>
</orm:Tables>
