=== OSAMES/ORM/OsamesMicroOrm/Config/xml_schemas/sqlTemplates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--/*
This file is part of OSAMES Micro ORM.
Copyright 2014 OSAMES

OSAMES Micro ORM is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OSAMES Micro ORM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with OSAMES Micro ORM.  If not, see <http://www.gnu.org/licenses/>.
*/-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.osames.org/osamesorm" xmlns:orm="http://www.osames.org/osamesorm" targetNamespace="http://www.osames.org/osamesorm" elementFormDefault="qualified">
    <xs:annotation>
        <xs:appinfo>OSAMES ORM Note</xs:appinfo>
        <xs:documentation xml:lang="en">
            This Schema defines a OSAMES ORM Sql Template.
        </xs:documentation>
    </xs:annotation>
    <xs:complexType name="TypeQueryList">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="Inserts">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="1" name="Insert">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
                <xs:unique name="UniqueInsertName">
                    <xs:selector xpath="orm:Insert"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Updates">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="1" name="Update">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
                <xs:unique name="UpdateUniqueName">
                    <xs:selector xpath="orm:Update"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Selects">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="1" name="Select">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
                <xs:unique name="SelectUniqueName">
                    <xs:selector xpath="orm:Select"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Deletes">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="1" name="Delete">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
                <xs:unique name="DeleteUniqueName">
                    <xs:selector xpath="orm:Delete"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="1" name="ProviderSpecific">
                <xs:complexType>
                    <xs:sequence>
                        <!-- sequence of abstractProvider complex type, using "Provider" element name -->
                        <xs:element maxOccurs="unbounded" minOccurs="1" name="Provider" type="abstractProvider" />
                    </xs:sequence>                    
                </xs:complexType>
                <xs:unique name="ProviderUnique">
                    <xs:selector xpath="orm:Provider"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="QueryList" type="TypeQueryList"/>
  
    <!-- ## ABSTRACT ## -->
    <!-- abstract type for "Provider" tag, which defines name attribute and Select child tags -->
    <xs:complexType name="abstractProvider" abstract="true">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Select">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
 
    <!-- ## EXTENSIONS OF ABSTRACT TYPE ## -->
    <!-- extension of abstractProvider with single field encloser -->
    <xs:complexType name="singleFieldEncloserType">
        <xs:complexContent>
            <xs:extension base="abstractProvider">
                <xs:attributeGroup ref="singleFieldEncloser" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <!-- extension of abstractProvider with two field enclosers -->
    <xs:complexType name="twoFieldEnclosersType">
        <xs:complexContent>
            <xs:extension base="abstractProvider">
                <xs:attributeGroup ref="twoFieldEnclosers" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <!-- ### ATTRIBUTE GROUPS ## -->
    <!-- FieldEncloser attribute definition -->
    <xs:attributeGroup name="singleFieldEncloser">
        <xs:attribute name="FieldEncloser" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    
    <!-- StartFieldEncloser and EndFieldEncloser attributes definition -->
    <xs:attributeGroup name="twoFieldEnclosers">
        <xs:attribute name="StartFieldEncloser" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="EndFieldEncloser" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>        
</xs:schema>

=== OSAMES/ORM/OsamesMicroOrm/Config/sqltemplates.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--/*
This file is part of OSAMES Micro ORM.
Copyright 2014 OSAMES

OSAMES Micro ORM is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OSAMES Micro ORM is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with OSAMES Micro ORM.  If not, see <http://www.gnu.org/licenses/>.
*/-->
<orm:QueryList xmlns:orm="http://www.osames.org/osamesorm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.osames.org/osamesorm xml_schemas\sqlTemplates.xsd" >
  <orm:FieldEncloser start="[" end="]"/>
  <orm:Inserts>
    <orm:Insert name="BaseInsert">INSERT INTO {0} ({1}) values ({2});</orm:Insert>
    <orm:Insert name="OtherBaseInsert">INSERT INTO {0} ({1}) values ({2});</orm:Insert>
  </orm:Inserts>
  <orm:Updates>
    <!--<orm:Update name="BaseUpdate">UPDATE {0} SET {1} WHERE {2};</orm:Update>-->
    <orm:Update name="BaseUpdateOne">UPDATE {0} SET {1} WHERE {2} = {3};</orm:Update>
  </orm:Updates>
  <orm:Selects>
    <orm:Select name="BaseRead">SELECT {0} FROM {1};</orm:Select>
    <orm:Select name="BaseReadAll">SELECT * FROM {0};</orm:Select>
    <orm:Select name="BaseReadWhere">SELECT {0} FROM {1} WHERE {2} = {3};</orm:Select>
    <orm:Select name="BaseReadAllWhere">SELECT * FROM {0} WHERE {1} = {2};</orm:Select>
    <orm:Select name="BaseReadWhereAndWhere">SELECT {0} FROM {1} WHERE {2} = {3} AND {4} = {5};</orm:Select>
    <!-- custom select, read customer with 2 joins -->
    <orm:Select name="ReadSingleCustomer">SELECT {0} FROM {1} LEFT JOIN {2} ON {3} = {4} LEFT JOIN {5} ON {6} = {7} WHERE {8}={9};</orm:Select>
  </orm:Selects>
  <orm:Deletes>
    <orm:Delete name="BaseDeleteWhere">DELETE FROM {0} WHERE {1} = {2};</orm:Delete>
  </orm:Deletes>
  <orm:ProviderSpecific>
    <!-- SQLite -->
    <orm:Select name="getlastinsertid" provider="System.Data.SQLite">select last_insert_rowid();</orm:Select>
    <!-- MySQL -->
    <orm:Select name="getlastinsertid" provider="MySql.Data.MySqlClient">select last_insert_id();</orm:Select>
    <!-- MS SQL -->
    <orm:Select name="getlastinsertid" provider="System.Data.SqlClient">select scope_identity()</orm:Select>
    <!-- Oracle -->
    <orm:Select name="getlastinsertid" provider="System.Data.OracleClient"></orm:Select>
    <!-- SQL Server Compact -->
    <orm:Select name="getlastinsertid" provider="System.Data.SqlServerCe.4.0"></orm:Select>
  </orm:ProviderSpecific>
</orm:QueryList>

=== OSAMES/ORM/TestOsamesMicroOrm/TestConfig/sqltemplates-test-other-sections-order.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- Interverted sections -->
<orm:QueryList xmlns:orm="http://www.osames.org/osamesorm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.osames.org/osamesorm ../Config/xml_schemas/sqlTemplates.xsd">
  <orm:Updates>  
    <orm:Update name="BaseUpdateOne">UPDATE {0} SET {1} WHERE {2} = {3};</orm:Update>
  </orm:Updates>
  <orm:Inserts>
    <orm:Insert name="BaseInsert">INSERT INTO {0} ({1}) values ({2});</orm:Insert>
  </orm:Inserts>
  <orm:Selects>
    <orm:Select name="BaseRead">SELECT {0} FROM {1};</orm:Select>
    <orm:Select name="BaseReadWhere">SELECT {0} FROM {1} WHERE {2} = {3};</orm:Select>
    <orm:Select name="BaseReadWhereAndWhere">SELECT {0} FROM {1} WHERE {2} = {3} AND {4} = {5};</orm:Select>
    <!-- custom select, read customer with 2 joins -->
    <orm:Select name="ReadSingleCustomer">SELECT {0} FROM {1} LEFT JOIN {2} ON {3} = {4} LEFT JOIN {5} ON {6} = {7} WHERE {8}={9};</orm:Select> 
  </orm:Selects>
  <orm:Deletes>
    <orm:Delete name="BaseDeleteWhere">DELETE FROM {0} WHERE {1} = {2};</orm:Delete>
  </orm:Deletes>
  <orm:ProviderSpecific>
    <!-- SQLite -->
    <orm:Provider xsi:type="orm:DoubleFE" name="System.Data.SQLite" StartFieldEncloser="[" EndFieldEncloser="]">
      <orm:Select name="getlastinsertid">select last_insert_rowid();</orm:Select>
    </orm:Provider>
    <!-- MySQL -->
    <orm:Provider xsi:type="orm:SingleFE" name="MySql.Data.MySqlClient" FieldEncloser="`">
      <orm:Select name="getlastinsertid">select last_insert_id();</orm:Select>
    </orm:Provider>
    <!-- MS SQL -->
    <orm:Provider xsi:type="orm:DoubleFE" name="System.Data.SqlClient" StartFieldEncloser="[" EndFieldEncloser="]">
      <orm:Select name="getlastinsertid">select scope_identity()</orm:Select>
    </orm:Provider>
    <!-- Oracle -->
    <orm:Provider xsi:type="orm:DoubleFE" name="### ORACLE ###" StartFieldEncloser="" EndFieldEncloser="">
    </orm:Provider>
    <!-- SQL Server Compact -->
    <orm:Provider xsi:type="orm:DoubleFE" name="### SQL Server Compact ###" StartFieldEncloser="" EndFieldEncloser="">
    </orm:Provider>
  </orm:ProviderSpecific>
</orm:QueryList>
